# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py
git:
  depth: 20

language: python
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7-dev

matrix:
  allow_failures:
    - python: 3.7-dev

install:
  - pip install --upgrade setuptools pip
  - python setup.py build bdist_wheel
  - pip install -e .[test]

script:
  ## Test if `pip install .[test]` installs all deps.
  - pytest -v test.py
